#!/usr/bin/env php
<?php

require_once __DIR__ . \DIRECTORY_SEPARATOR . 'vendor'. \DIRECTORY_SEPARATOR .'autoload.php';

use tpr\Path;
use tpr\App;

Path::configurate([
    'root'  => __DIR__ . \DIRECTORY_SEPARATOR,
    'vendor'=> Path::join(Path::root(), 'vendor')
]);

App::default()->config([
    'namespace'      => 'app\commands',
    'server_options' => [
        'commands' => [
            'make' => \tpr\command\Make::class
        ]
    ]
])->run();
