#!/usr/bin/env php
<?php

namespace tpr;

require_once __DIR__ . '/vendor/autoload.php';

Path::root(__DIR__ . \DIRECTORY_SEPARATOR);
Path::vendor(Path::root() . 'vendor' . \DIRECTORY_SEPARATOR);

App::debugMode(true);
App::default()
    ->setOption("namespace", "app\\command")
    ->run();